#!/bin/bash

function ping_gateway()
{
	ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo 0 || echo -1
}

function check_connection()
{
	if [ $(ping_gateway) -eq 0 ]; then
		echo "Connected"
	else # [ping_gateway -ne 0]
		echo "Not Connected"
	fi
}
check_connection
