#!/bin/bash
FILENAME=$1

# Error when no input
if [ $# -eq 0 ]; then
  echo No input file.
  exit 1
fi

# Error when not readable
if [ ! -f "$FILENAME" ]; then
  echo File does not exist.
  exit 1
elif [ ! -r "$FILENAME" ]; then
  echo File not readable.
  exit 1
elif [ ! -s "$FILENAME" ]; then
  echo File is empty.
  exit 1
else
  gnome-open "$FILENAME"
fi
